apiVersion: v1
kind: ConfigMap
metadata: { name: otel-config, namespace: telemetry }
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http: {}
          grpc: {}
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      loki:
        endpoint: http://loki.telemetry.svc:3100/loki/api/v1/push
      otlp:
        endpoint: tempo.telemetry.svc:4317
        tls: { insecure: true }
    processors: { batch: {} }
    service:
      pipelines:
        metrics: { receivers: [otlp], processors: [batch], exporters: [prometheus] }
        traces: { receivers: [otlp], processors: [batch], exporters: [otlp] }
